#!/usr/bin/env python3
"""Generate registry/sdk-schema-index.yaml from compiled JARs.

Usage:
    python3 -m velocity_converter.build_schema_index \
        --customer-jar build/customer-config.jar \
        --datamodel-jar build/core-datamodel-v1.7.61.jar \
        --product ZenCover \
        --out registry/sdk-schema-index.yaml \
        [--depth 3]

Exits non-zero if JARs are missing or no root types are found.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from velocity_converter.sdk_introspect import (
    _default_datamodel_jar,
    build_schema_index,
    roots_for_product,
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate sdk-schema-index.yaml from JARs.")
    ap.add_argument("--customer-jar", type=Path, default=None)
    ap.add_argument("--datamodel-jar", type=Path, default=None)
    ap.add_argument("--product", required=True, help="Product name, e.g. ZenCover")
    ap.add_argument("--out", type=Path, default=None,
                    help="Output path (default: registry/sdk-schema-index.yaml)")
    ap.add_argument("--depth", type=int, default=3, help="BFS depth (default: 3)")
    args = ap.parse_args()

    repo_root = _repo_root()
    customer_jar = args.customer_jar or (repo_root / "build" / "customer-config.jar")
    if not customer_jar.exists():
        print(f"ERROR: customer jar not found: {customer_jar}", file=sys.stderr)
        return 1

    datamodel_jar = args.datamodel_jar or _default_datamodel_jar(repo_root)
    if datamodel_jar is None or not datamodel_jar.exists():
        print("ERROR: no core-datamodel jar found (pass --datamodel-jar)", file=sys.stderr)
        return 1

    classpath = f"{customer_jar}:{datamodel_jar}"

    # Resolve rendering root FQCNs for quote and segment.
    roots = roots_for_product(args.product, ["quote", "segment"])
    root_fqcns = [r["java_type"] for r in roots if r.get("java_type")]
    if not root_fqcns:
        print(f"ERROR: no resolvable root FQCNs for product {args.product!r}", file=sys.stderr)
        return 1

    print(f"Building schema index: product={args.product}, depth={args.depth}")
    print(f"  Roots: {root_fqcns}")
    index = build_schema_index(classpath, root_fqcns, max_depth=args.depth)

    if not index:
        print("ERROR: schema index is empty — check JARs and product name", file=sys.stderr)
        return 1

    out_path = args.out or (repo_root / "registry" / "sdk-schema-index.yaml")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Generated by velocity_converter/build_schema_index.py\n"
        f"# Source: {customer_jar.name} + {datamodel_jar.name}\n"
        f"# Product: {args.product}  Depth: {args.depth}\n\n"
    )
    body = yaml.dump(index, sort_keys=True, allow_unicode=True,
                     default_flow_style=False, width=120)
    out_path.write_text(header + body, encoding="utf-8")

    field_count = sum(len(v["fields"]) for v in index.values())
    print(f"Wrote {out_path}")
    print(f"{len(index)} entity types  ·  {field_count} fields  ·  depth {args.depth}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
