#!/usr/bin/env python3
"""Leg 4 — Document Data Snapshot Plugin Generator.

Reads:
  - <stem>.suggested.yaml  (Leg 2) — provides `product:` and `variables:`
  - build/customer-config.jar       — plugin interface + {Product}* request types
  - build/core-datamodel-*.jar      — DocumentDataSnapshot, Policy, Transaction, ...

Writes:
  - {Product}DocumentDataSnapshotPluginImpl.java  — one plugin class per product
  - <stem>.plugin-report.md                        — path-validation + ignored fields

Deterministic Java codegen (no LLM). renderingData root ($data in Velocity) is
the full quote / segment object — Velocity navigates it (D3). Only high-confidence
variables are validated; medium/low are reported as ignored (D5). Missing segment
on a policy request fails loud at runtime (D10). See the Leg 4 plan §3 for the
locked decisions behind these choices.
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from pathlib import Path

import yaml

# Shared SDK-introspection helpers (Leg 2 plan P1.1 — single source of JAR truth).
from sdk_introspect import (
    CUSTOMER_PACKAGE,
    INVOICE_REQUEST,
    PLUGIN_INTERFACE,
    _class_exists,
    _default_datamodel_jar,
    validate_path,
)


# ---------------------------------------------------------------------------
# Helpers (mirrors scripts/leg3_substitute.py)
# ---------------------------------------------------------------------------


def _repo_root() -> Path:
    """Walk up from this script until a .cursor/ directory is found."""
    p = Path(__file__).resolve().parent
    for candidate in [p, *p.parents]:
        if (candidate / ".cursor").is_dir():
            return candidate
    return Path(__file__).resolve().parent.parent


def _rel(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path)


def _load_yaml(path: Path) -> dict:
    """Load YAML, tolerating # comment-header lines Leg 2 writes."""
    lines = path.read_text(encoding="utf-8").splitlines()
    body = "\n".join(ln for ln in lines if not ln.startswith("#"))
    data = yaml.safe_load(body)
    return data if isinstance(data, dict) else {}


# JAR introspection (_javap / _zero_arg_methods / _unwrap_type / validate_path /
# _default_datamodel_jar / _class_exists) now lives in scripts/sdk_introspect.py
# and is imported above — single source of truth shared with Leg 2 (plan P1.1).


# ---------------------------------------------------------------------------
# Java codegen
# ---------------------------------------------------------------------------


JAVA_TEMPLATE = """package com.socotra.deployment.customer;

import com.socotra.coremodel.DocumentDataSnapshot;
import com.socotra.coremodel.Policy;
import com.socotra.coremodel.Transaction;
import com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(invoice_request)s;
import com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(quote_request)s;
import com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(policy_request)s;

import java.util.Collections;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by scripts/leg4_generate_plugin.py from %(suggested_name)s — review
 * before deploying to Socotra.
 * renderingData root ($data in Velocity) = full quote or segment object.
 */
public class %(class_name)s implements DocumentDataSnapshotPlugin {

    private static final Logger log =
            LoggerFactory.getLogger(%(class_name)s.class);

    @Override
    public DocumentDataSnapshot dataSnapshot(%(quote_request)s request) {
        return DocumentDataSnapshot.builder()
                .renderingData(request.quote())
                .build();
    }

    @Override
    public DocumentDataSnapshot dataSnapshot(%(policy_request)s request) {
        %(segment_type)s segment = request.segment()
                .orElseThrow(() -> {
                    String docName = request.config() != null ? request.config().name() : "unknown";
                    Policy policy = request.policy();
                    Transaction tx = request.transaction();
                    log.error(
                            "Document data snapshot requires a segment but none was present "
                                    + "(document={}, policyLocator={}, transactionCategory={})",
                            docName,
                            policy != null ? policy.locator() : null,
                            tx != null ? tx.transactionCategory() : null);
                    return new IllegalStateException(
                            "Segment required for document data snapshot (document=" + docName + ")");
                });
        return DocumentDataSnapshot.builder()
                .renderingData(segment)
                .build();
    }

    @Override
    public DocumentDataSnapshot dataSnapshot(%(invoice_request)s request) {
        // TODO: invoice-scoped renderingData when invoice documents use this pipeline
        log.warn("Invoice document data snapshot not implemented — returning empty renderingData");
        return DocumentDataSnapshot.builder()
                .renderingData(Collections.emptyMap())
                .build();
    }
}
"""


def render_java(product: str, suggested_name: str) -> str:
    return JAVA_TEMPLATE % {
        "class_name": f"{product}DocumentDataSnapshotPluginImpl",
        "quote_request": f"{product}QuoteRequest",
        "policy_request": f"{product}Request",
        "invoice_request": INVOICE_REQUEST,
        "segment_type": f"{product}Segment",
        "suggested_name": suggested_name,
    }


# ---------------------------------------------------------------------------
# Report writer (plan §13)
# ---------------------------------------------------------------------------


def write_report(
    report_path: Path,
    *,
    stem: str,
    product: str,
    suggested_path: Path,
    java_path: Path,
    high_results: list[tuple[dict, str, str]],
    ignored_vars: list[dict],
    compile_status: str | None,
    compile_detail: str,
    generated_at: str,
) -> None:
    seg = f"{product}Segment"
    quote = f"{product}Quote"
    lines: list[str] = [
        "<!-- leg4_schema_version: 1.0 -->",
        "",
        f"# Leg 4 Plugin Report — {stem}",
        "",
        "| | |",
        "|---|---|",
        f"| **Product** | {product} |",
        f"| **Suggested mapping** | `{suggested_path.name}` |",
        f"| **Generated Java** | `{java_path.name}` |",
        f"| **Generated** | {generated_at} |",
        "",
        "---",
        "",
        "## Rendering strategy",
        "",
        f"Pass the full `{seg}` (policy documents) / `{quote}` (quote documents) "
        "object as `renderingData` (D3). Velocity navigates it via `$data.*`.",
        "",
        "---",
        "",
        f"## High-confidence paths (validated against `{seg}`) ({len(high_results)})",
        "",
    ]
    if high_results:
        lines += [
            "| Variable | data_source | javap | detail |",
            "|---|---|---|---|",
        ]
        for v, status, detail in high_results:
            name = v.get("name") or ""
            ds = v.get("data_source") or ""
            lines.append(f"| {name} | `{ds}` | {status} | {detail} |")
        if any(s == "warning" for _, s, _ in high_results):
            lines += [
                "",
                "> **Warnings are non-fatal.** A warning means the path was not found on "
                f"`{seg}` via `javap`. The plugin still passes the whole object, so the path "
                "will resolve at runtime if it exists on the live model, or must be supplied "
                "by a future plugin enhancement (`next-action: supply-from-plugin`).",
            ]
    else:
        lines.append("_No high-confidence variables with a data_source._")
    lines += ["", "---", ""]

    lines += [
        f"## Ignored — medium / low confidence ({len(ignored_vars)})",
        "",
        "Not validated and not used for codegen in the MVP (D5). The full object is "
        "passed as `renderingData`, so confirmed paths still resolve at runtime once "
        "promoted to `high` in the `.suggested.yaml`.",
        "",
        "| Variable | confidence | data_source |",
        "|---|---|---|",
    ]
    for v in ignored_vars:
        name = v.get("name") or ""
        conf = v.get("confidence") or ""
        ds = v.get("data_source") or ""
        lines.append(f"| {name} | {conf} | `{ds or '(empty)'}` |")
    lines += ["", "---", ""]

    lines += ["## Compile check", ""]
    if compile_status is None:
        lines.append("_Skipped — re-run with `--compile-check` to verify against the JARs._")
    else:
        lines.append(f"**{compile_status}**")
        if compile_detail:
            lines += ["", "```", compile_detail.strip(), "```"]
    lines += [""]

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Compile check (plan §14)
# ---------------------------------------------------------------------------


def compile_check(
    java_path: Path,
    customer_jar: Path,
    datamodel_jar: Path,
    slf4j_jar: Path,
    out_dir: Path,
) -> tuple[bool, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    cp = ":".join(str(p) for p in (customer_jar, datamodel_jar, slf4j_jar))
    cmd = [
        "javac", "-encoding", "UTF-8",
        "-cp", cp,
        "-d", str(out_dir),
        str(java_path),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    detail = (proc.stdout + proc.stderr).strip() or f"javac -cp {cp}"
    return proc.returncode == 0, detail


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> int:
    repo_root = _repo_root()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--suggested", type=Path, required=True,
                    help=".suggested.yaml produced by Leg 2")
    ap.add_argument("--output-dir", type=Path, default=None,
                    help="Where to write the .java (default: dir of --suggested)")
    ap.add_argument("--customer-jar", type=Path,
                    default=repo_root / "build" / "customer-config.jar",
                    help="customer-config.jar with the plugin interface + request types")
    ap.add_argument("--datamodel-jar", type=Path, default=None,
                    help="core-datamodel-v*.jar (default: newest under build/)")
    ap.add_argument("--slf4j-jar", type=Path,
                    default=repo_root / "build" / "slf4j-api-1.7.36.jar",
                    help="slf4j-api jar for the compile check")
    ap.add_argument("--compile-check", action="store_true", default=False,
                    help="Run javac against the JARs after generating")
    args = ap.parse_args()

    suggested_path = args.suggested.resolve()
    if not suggested_path.exists():
        print(f"ERROR: suggested file not found: {suggested_path}", file=sys.stderr)
        return 1

    stem = suggested_path.name
    for suffix in (".suggested.yaml", ".yaml"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break

    out_dir = (args.output_dir.resolve() if args.output_dir else suggested_path.parent)

    customer_jar = args.customer_jar.resolve()
    if not customer_jar.exists():
        print(f"ERROR: customer jar not found: {customer_jar}", file=sys.stderr)
        return 1

    datamodel_jar = (
        args.datamodel_jar.resolve() if args.datamodel_jar
        else (_default_datamodel_jar(repo_root) or None)
    )
    if datamodel_jar is None or not datamodel_jar.exists():
        print("ERROR: no core-datamodel jar found (pass --datamodel-jar)", file=sys.stderr)
        return 1

    suggested = _load_yaml(suggested_path)
    product = (suggested.get("product") or "").strip()
    if not product:
        print(f"ERROR: 'product' missing from {suggested_path.name}", file=sys.stderr)
        return 1

    classpath = f"{customer_jar}:{datamodel_jar}"

    # --- Verify interface + nested request types via javap (fail fast) -------
    if not _class_exists(classpath, PLUGIN_INTERFACE):
        print(f"ERROR: {PLUGIN_INTERFACE} not found in {customer_jar.name}", file=sys.stderr)
        return 1

    required_nested = {
        "quote request": f"{PLUGIN_INTERFACE}${product}QuoteRequest",
        "policy request": f"{PLUGIN_INTERFACE}${product}Request",
        "invoice request": f"{PLUGIN_INTERFACE}${INVOICE_REQUEST}",
    }
    missing = [f"{label} ({fqcn})" for label, fqcn in required_nested.items()
               if not _class_exists(classpath, fqcn)]
    if missing:
        print("ERROR: required plugin types not found in JAR:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1

    segment_fqcn = f"{CUSTOMER_PACKAGE}.{product}Segment"
    segment_ok = _class_exists(classpath, segment_fqcn)

    # --- Render + write Java -------------------------------------------------
    class_name = f"{product}DocumentDataSnapshotPluginImpl"
    java_path = out_dir / f"{class_name}.java"
    out_dir.mkdir(parents=True, exist_ok=True)
    java_path.write_text(render_java(product, suggested_path.name), encoding="utf-8")

    # --- Categorise + validate variables -------------------------------------
    variables = suggested.get("variables") or []
    high_vars = [
        v for v in variables
        if (v.get("confidence") or "").lower() == "high"
        and (v.get("data_source") or "").strip()
    ]
    ignored_vars = [v for v in variables if v not in high_vars]

    high_results: list[tuple[dict, str, str]] = []
    for v in high_vars:
        if segment_ok:
            status, detail = validate_path(classpath, segment_fqcn, v.get("data_source") or "")
        else:
            status, detail = "warning", f"segment type {segment_fqcn} not found in JAR"
        high_results.append((v, status, detail))

    # --- Optional compile check ----------------------------------------------
    compile_status: str | None = None
    compile_detail = ""
    compile_ok = True
    if args.compile_check:
        compile_ok, compile_detail = compile_check(
            java_path, customer_jar, datamodel_jar, args.slf4j_jar.resolve(),
            repo_root / "build" / "tmp" / "leg4-compile",
        )
        compile_status = "PASS" if compile_ok else "FAIL"

    # --- Report --------------------------------------------------------------
    report_path = suggested_path.parent / f"{stem}.plugin-report.md"
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    write_report(
        report_path,
        stem=stem,
        product=product,
        suggested_path=suggested_path,
        java_path=java_path,
        high_results=high_results,
        ignored_vars=ignored_vars,
        compile_status=compile_status,
        compile_detail=compile_detail,
        generated_at=generated_at,
    )

    print(f"Wrote {_rel(java_path, repo_root)}")
    print(f"Wrote {_rel(report_path, repo_root)}")
    print(
        f"Product={product}  high={len(high_results)}  ignored={len(ignored_vars)}"
        + (f"  compile={compile_status}" if compile_status else "")
    )

    if args.compile_check and not compile_ok:
        print("ERROR: compile check failed:\n" + compile_detail, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
