#!/usr/bin/env python3
"""Leg 4 — Document Data Snapshot Plugin Generator.

Reads:
  - <stem>.suggested.yaml  (Leg 2) — provides `product:` and `variables:`
  - build/customer-config.jar       — plugin interface + {Product}* request types
  - build/core-datamodel-*.jar      — DocumentDataSnapshot, Policy, Transaction, ...

Writes:
  - {Product}DocumentDataSnapshotPluginImpl.java  — one plugin class per product
  - <stem>.plugin-report.md                        — path-validation + ignored fields

Deterministic Java codegen (no LLM). renderingData is a HashMap<String, Object>
with named keys per request type:

  quote request   → keys: "quote" ($data.quote.*), "pricing" (enriched), "productType"
  policy request  → keys: "policy" ($data.policy.*), "transaction" ($data.transaction.*),
                          "segment" ($data.segment.*), "todayAsString", "productType"

Only high-confidence variables are validated; medium/low are reported as ignored (D5).
Missing segment on a policy request fails soft — logs an error, segment key is null.
See the Leg 4 renderingData-alignment plan for the decisions behind these choices.
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from pathlib import Path

import yaml

# Shared SDK-introspection helpers (Leg 2 plan P1.1 — single source of JAR truth).
from sdk_introspect import (
    CUSTOMER_PACKAGE,
    DATAFETCHER_INTERFACE,
    INVOICE_REQUEST,
    PLUGIN_INTERFACE,
    _class_exists,
    _default_datamodel_jar,
    _default_slf4j_jar,
    _method_return_type,
    _unwrap_type,
    validate_path,
)


# ---------------------------------------------------------------------------
# Helpers (mirrors scripts/leg3_substitute.py)
# ---------------------------------------------------------------------------


def _repo_root() -> Path:
    """Walk up from this script until a .cursor/ directory is found."""
    p = Path(__file__).resolve().parent
    for candidate in [p, *p.parents]:
        if (candidate / ".cursor").is_dir():
            return candidate
    return Path(__file__).resolve().parent.parent


def _rel(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path)


def _load_yaml(path: Path) -> dict:
    """Load YAML, tolerating # comment-header lines Leg 2 writes."""
    lines = path.read_text(encoding="utf-8").splitlines()
    body = "\n".join(ln for ln in lines if not ln.startswith("#"))
    data = yaml.safe_load(body)
    return data if isinstance(data, dict) else {}


def _flatten_to_segment_root(suggested: dict) -> dict:
    """Normalise schema 2.0 per-root verdicts to flat scalar fields using the segment root.

    Leg 4 specifically validates paths against the segment root (D5 — MVP). For schema
    1.x files (no rendering_roots), returns the dict unchanged.
    """
    roots = suggested.get("rendering_roots") or []
    if not roots:
        return suggested

    seg_id = next((r.get("id") for r in roots if r.get("id") == "segment"), None)
    if seg_id is None:
        seg_id = roots[0].get("id")
    if not seg_id:
        return suggested

    def _promote(entry: dict) -> dict:
        verdict = (entry.get("verdicts") or {}).get(seg_id) or {}
        return {
            **entry,
            "data_source": verdict.get("data_source") or "",
            "confidence": verdict.get("confidence") or "",
            "reasoning": verdict.get("reasoning") or "",
        }

    new_vars = [_promote(v) for v in (suggested.get("variables") or [])]
    return {**suggested, "variables": new_vars}


# JAR introspection (_javap / _zero_arg_methods / _unwrap_type / validate_path /
# _default_datamodel_jar / _class_exists) now lives in scripts/sdk_introspect.py
# and is imported above — single source of truth shared with Leg 2 (plan P1.1).


# ---------------------------------------------------------------------------
# Java codegen
# ---------------------------------------------------------------------------


JAVA_TEMPLATE = """package com.socotra.deployment.customer;

import com.socotra.coremodel.Charge;
import com.socotra.coremodel.DocumentDataSnapshot;
import com.socotra.coremodel.Policy;
import com.socotra.coremodel.QuotePricing;
import com.socotra.coremodel.Transaction;
import com.socotra.deployment.DataFetcherFactory;
%(dynamic_imports)simport com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(invoice_request)s;
import com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(quote_request)s;
import com.socotra.deployment.customer.DocumentDataSnapshotPlugin.%(policy_request)s;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by scripts/leg4_generate_plugin.py from %(suggested_name)s — review
 * before deploying to Socotra.
 * renderingData is a HashMap<String, Object> with named keys per request type.
 */
public class %(class_name)s implements DocumentDataSnapshotPlugin {

    private static final Logger log =
            LoggerFactory.getLogger(%(class_name)s.class);

    @Override
    public DocumentDataSnapshot dataSnapshot(%(quote_request)s request) {
        %(quote_type)s quote = request.quote();
        QuotePricing pricing = null;
        try {
            pricing = DataFetcherFactory.get().getQuotePricing(quote.locator());
        } catch (Exception e) {
            log.warn("Could not fetch quote pricing for locator={}", quote.locator(), e);
        }

        HashMap<String, Object> renderingData = new HashMap<>();
        DecimalFormat df = new DecimalFormat("0.00");
        BigDecimal premiumTotal = BigDecimal.ZERO;
        BigDecimal otherTotal = BigDecimal.ZERO;

        if (pricing != null && pricing.items() != null) {
            for (Charge item : pricing.items()) {
                if ("premium".equalsIgnoreCase(item.chargeCategory().toString())) {
                    premiumTotal = premiumTotal.add(item.amount());
                } else if (!"nonFinancial".equalsIgnoreCase(item.chargeCategory().toString())) {
                    otherTotal = otherTotal.add(item.amount());
                }
            }
        }

        BigDecimal totalBillable = premiumTotal.add(otherTotal);
        HashMap<String, Object> enhancedPricing = new HashMap<>();
        enhancedPricing.put("premiumTotal", df.format(premiumTotal));
        enhancedPricing.put("otherTotal", df.format(otherTotal));
        enhancedPricing.put("totalBillable", df.format(totalBillable));

        renderingData.put("quote", quote);
        renderingData.put("pricing", enhancedPricing);
        renderingData.put("productType", "%(product)s");
%(quote_datafetcher_extras)s
        return DocumentDataSnapshot.builder()
                .renderingData(renderingData)
                .build();
    }

    @Override
    public DocumentDataSnapshot dataSnapshot(%(policy_request)s request) {
        Policy policy = request.policy();
        Transaction transaction = request.transaction();
        %(segment_type)s segment = request.segment().orElse(null);

        if (segment == null) {
            log.error("Segment is missing in the %(product)s request");
        }

        HashMap<String, Object> renderingData = new HashMap<>();
        String pattern = "MM/dd/yyyy";
        DateFormat dateFormatter = new SimpleDateFormat(pattern);
        Date today = Calendar.getInstance().getTime();
        String todayAsString = dateFormatter.format(today);

        renderingData.put("todayAsString", todayAsString);
        renderingData.put("policy", policy);
        renderingData.put("transaction", transaction);
        renderingData.put("segment", segment);
        renderingData.put("productType", "%(product)s");
%(policy_datafetcher_extras)s
        return DocumentDataSnapshot.builder()
                .renderingData(renderingData)
                .build();
    }

    @Override
    public DocumentDataSnapshot dataSnapshot(%(invoice_request)s request) {
        // TODO: invoice-scoped renderingData when invoice documents use this pipeline
        log.warn("Invoice document data snapshot not implemented — returning empty renderingData");
        return DocumentDataSnapshot.builder()
                .renderingData(Collections.emptyMap())
                .build();
    }
}
"""


_LEGACY_PRICING_KEYS = frozenset({"pricing"})


def _collect_datafetcher_calls(
    suggested: dict, root_id: str, classpath: str, skip_keys: frozenset = frozenset()
) -> list[dict]:
    """Return deduplicated DataFetcher calls for the given root from the suggested mapping.

    Only includes entries where candidate.source == 'datafetcher' AND the verdict for
    root_id is high or medium confidence. Keys in skip_keys are excluded (used to avoid
    duplicating legacy hardcoded puts like 'pricing').
    """
    seen: dict[str, dict] = {}
    for v in (suggested.get("variables") or []):
        cand = v.get("candidate") or {}
        if cand.get("source") != "datafetcher":
            continue
        verdict = (v.get("verdicts") or {}).get(root_id) or {}
        if verdict.get("confidence") not in ("high", "medium"):
            continue
        key = cand.get("datafetcher_key", "")
        method = cand.get("datafetcher_method", "")
        arg_raw = cand.get("datafetcher_arg", "")
        arg = arg_raw.get(root_id, "") if isinstance(arg_raw, dict) else str(arg_raw)
        if key and method and key not in seen and key not in skip_keys:
            seen[key] = {"key": key, "method": method, "arg": arg}

    result = []
    for info in seen.values():
        raw_ret = _method_return_type(classpath, DATAFETCHER_INTERFACE, info["method"])
        fqcn = _unwrap_type(raw_ret) if raw_ret else None
        short = fqcn.rsplit(".", 1)[-1] if fqcn else "Object"
        result.append({
            "key": info["key"],
            "method": info["method"],
            "arg": info["arg"],
            "return_type": short,
            "return_fqcn": fqcn or "",
        })
    return result


def _generate_datafetcher_extras(calls: list[dict]) -> str:
    """Generate null-guarded DataFetcher put blocks (indented 8 spaces)."""
    if not calls:
        return ""
    blocks = []
    for c in calls:
        key, method, arg, ret = c["key"], c["method"], c["arg"], c["return_type"]
        blocks.append(
            f"        {ret} {key} = null;\n"
            f"        try {{\n"
            f"            {key} = DataFetcherFactory.get().{method}({arg});\n"
            f"        }} catch (Exception e) {{\n"
            f"            log.warn(\"Could not fetch {key} for locator={{}}\", {arg}, e);\n"
            f"        }}\n"
            f"        if ({key} != null) {{\n"
            f"            renderingData.put(\"{key}\", {key});\n"
            f"        }}"
        )
    return "\n".join(blocks)


def _generate_dynamic_imports(all_calls: list[dict]) -> str:
    fqcns = sorted({
        c["return_fqcn"] for c in all_calls
        if c["return_fqcn"] and c["return_type"] != "Object"
    })
    return "\n".join(f"import {fqcn};" for fqcn in fqcns)


def render_java(
    product: str,
    suggested_name: str,
    quote_df_calls: list[dict] | None = None,
    policy_df_calls: list[dict] | None = None,
) -> str:
    quote_extras = _generate_datafetcher_extras(quote_df_calls or [])
    policy_extras = _generate_datafetcher_extras(policy_df_calls or [])
    all_calls = (quote_df_calls or []) + (policy_df_calls or [])
    dyn_imports = _generate_dynamic_imports(all_calls)
    if dyn_imports:
        dyn_imports = dyn_imports + "\n"
    return JAVA_TEMPLATE % {
        "class_name": f"{product}DocumentDataSnapshotPluginImpl",
        "quote_request": f"{product}QuoteRequest",
        "quote_type": f"{product}Quote",
        "policy_request": f"{product}Request",
        "invoice_request": INVOICE_REQUEST,
        "segment_type": f"{product}Segment",
        "product": product,
        "suggested_name": suggested_name,
        "quote_datafetcher_extras": ("\n" + quote_extras) if quote_extras else "",
        "policy_datafetcher_extras": ("\n" + policy_extras) if policy_extras else "",
        "dynamic_imports": dyn_imports,
    }


# ---------------------------------------------------------------------------
# Report writer (plan §13)
# ---------------------------------------------------------------------------


def write_report(
    report_path: Path,
    *,
    stem: str,
    product: str,
    suggested_path: Path,
    java_path: Path,
    high_results: list[tuple[dict, str, str]],
    ignored_vars: list[dict],
    compile_status: str | None,
    compile_detail: str,
    generated_at: str,
) -> None:
    seg = f"{product}Segment"
    quote = f"{product}Quote"
    lines: list[str] = [
        "<!-- leg4_schema_version: 1.0 -->",
        "",
        f"# Leg 4 Plugin Report — {stem}",
        "",
        "| | |",
        "|---|---|",
        f"| **Product** | {product} |",
        f"| **Suggested mapping** | `{suggested_path.name}` |",
        f"| **Generated Java** | `{java_path.name}` |",
        f"| **Generated** | {generated_at} |",
        "",
        "---",
        "",
        "## Rendering strategy",
        "",
        f"renderingData is a `HashMap<String, Object>` with named keys per request type:",
        "",
        f"- **Quote request** — `\"quote\"` (`{quote}`), `\"pricing\"` (enriched totals), `\"productType\"`",
        f"  Velocity: `$data.quote.*`, `$data.pricing.*`",
        f"- **Policy request** — `\"policy\"` (`Policy`), `\"transaction\"` (`Transaction`), "
        f"`\"segment\"` (`{seg}`), `\"todayAsString\"`, `\"productType\"`",
        f"  Velocity: `$data.policy.*`, `$data.transaction.*`, `$data.segment.*`",
        "",
        "---",
        "",
        f"## High-confidence paths (validated against `{seg}` or `{quote}`) ({len(high_results)})",
        "",
    ]
    if high_results:
        lines += [
            "| Variable | data_source | javap | detail |",
            "|---|---|---|---|",
        ]
        for v, status, detail in high_results:
            name = v.get("name") or ""
            ds = v.get("data_source") or ""
            lines.append(f"| {name} | `{ds}` | {status} | {detail} |")
        if any(s == "warning" for _, s, _ in high_results):
            lines += [
                "",
                "> **Warnings are non-fatal.** A warning means the path was not found via "
                "`javap`. The field may exist on the live model but not be visible through "
                "javap introspection, or must be supplied by a future plugin enhancement "
                "(`next-action: supply-from-plugin`).",
            ]
    else:
        lines.append("_No high-confidence variables with a data_source._")
    lines += ["", "---", ""]

    lines += [
        f"## Ignored — medium / low confidence ({len(ignored_vars)})",
        "",
        "Not validated in this run (D5). Promote to `high` in the `.suggested.yaml` "
        "to include in future validation runs.",
        "",
        "| Variable | confidence | data_source |",
        "|---|---|---|",
    ]
    for v in ignored_vars:
        name = v.get("name") or ""
        conf = v.get("confidence") or ""
        ds = v.get("data_source") or ""
        lines.append(f"| {name} | {conf} | `{ds or '(empty)'}` |")
    lines += ["", "---", ""]

    lines += ["## Compile check", ""]
    if compile_status is None:
        lines.append("_Skipped — re-run with `--compile-check` to verify against the JARs._")
    else:
        lines.append(f"**{compile_status}**")
        if compile_detail:
            lines += ["", "```", compile_detail.strip(), "```"]
    lines += [""]

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Compile check (plan §14)
# ---------------------------------------------------------------------------


def compile_check(
    java_path: Path,
    customer_jar: Path,
    datamodel_jar: Path,
    slf4j_jar: Path,
    out_dir: Path,
) -> tuple[bool, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    cp = ":".join(str(p) for p in (customer_jar, datamodel_jar, slf4j_jar))
    cmd = [
        "javac", "-encoding", "UTF-8",
        "-cp", cp,
        "-d", str(out_dir),
        str(java_path),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    detail = (proc.stdout + proc.stderr).strip() or f"javac -cp {cp}"
    return proc.returncode == 0, detail


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> int:
    repo_root = _repo_root()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--suggested", type=Path, required=True,
                    help=".suggested.yaml produced by Leg 2")
    ap.add_argument("--output-dir", type=Path, default=None,
                    help="Where to write the .java (default: dir of --suggested)")
    ap.add_argument("--customer-jar", type=Path,
                    default=repo_root / "build" / "customer-config.jar",
                    help="customer-config.jar with the plugin interface + request types")
    ap.add_argument("--datamodel-jar", type=Path, default=None,
                    help="core-datamodel-v*.jar (default: newest under build/)")
    ap.add_argument("--slf4j-jar", type=Path,
                    default=None,
                    help="slf4j-api jar for the compile check (default: auto-discover build/slf4j-api-*.jar)")
    ap.add_argument("--compile-check", action="store_true", default=False,
                    help="Run javac against the JARs after generating")
    args = ap.parse_args()

    suggested_path = args.suggested.resolve()
    if not suggested_path.exists():
        print(f"ERROR: suggested file not found: {suggested_path}", file=sys.stderr)
        return 1

    stem = suggested_path.name
    for suffix in (".suggested.yaml", ".yaml"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break

    out_dir = (args.output_dir.resolve() if args.output_dir else suggested_path.parent)

    customer_jar = args.customer_jar.resolve()
    if not customer_jar.exists():
        print(f"ERROR: customer jar not found: {customer_jar}", file=sys.stderr)
        return 1

    datamodel_jar = (
        args.datamodel_jar.resolve() if args.datamodel_jar
        else (_default_datamodel_jar(repo_root) or None)
    )
    if datamodel_jar is None or not datamodel_jar.exists():
        print("ERROR: no core-datamodel jar found (pass --datamodel-jar)", file=sys.stderr)
        return 1

    slf4j_jar = (
        args.slf4j_jar.resolve() if args.slf4j_jar
        else (_default_slf4j_jar(repo_root) or None)
    )
    if slf4j_jar is None or not slf4j_jar.exists():
        print("ERROR: no slf4j-api jar found (pass --slf4j-jar)", file=sys.stderr)
        return 1

    suggested_raw = _load_yaml(suggested_path)
    product = (suggested_raw.get("product") or "").strip()
    if not product:
        print(f"ERROR: 'product' missing from {suggested_path.name}", file=sys.stderr)
        return 1

    classpath = f"{customer_jar}:{datamodel_jar}"

    # Collect DataFetcher calls before flattening — needs per-root verdicts.
    # Skip "pricing" key for quote handler (handled by the legacy pricing computation block).
    quote_df_calls = _collect_datafetcher_calls(
        suggested_raw, "quote", classpath, skip_keys=_LEGACY_PRICING_KEYS
    )
    policy_df_calls = _collect_datafetcher_calls(
        suggested_raw, "segment", classpath, skip_keys=frozenset()
    )

    suggested = _flatten_to_segment_root(suggested_raw)

    # --- Verify interface + nested request types via javap (fail fast) -------
    if not _class_exists(classpath, PLUGIN_INTERFACE):
        print(f"ERROR: {PLUGIN_INTERFACE} not found in {customer_jar.name}", file=sys.stderr)
        return 1

    required_nested = {
        "quote request": f"{PLUGIN_INTERFACE}${product}QuoteRequest",
        "policy request": f"{PLUGIN_INTERFACE}${product}Request",
        "invoice request": f"{PLUGIN_INTERFACE}${INVOICE_REQUEST}",
    }
    missing = [f"{label} ({fqcn})" for label, fqcn in required_nested.items()
               if not _class_exists(classpath, fqcn)]
    if missing:
        print("ERROR: required plugin types not found in JAR:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1

    segment_fqcn = f"{CUSTOMER_PACKAGE}.{product}Segment"
    segment_ok = _class_exists(classpath, segment_fqcn)

    # Determine primary root for validation — prefer segment, fall back to quote.
    _vel_prefix_map = {"quote": "$data.quote", "segment": "$data.segment"}
    roots_list = suggested.get("rendering_roots") or []
    primary_root_id = next(
        (r["id"] for r in roots_list if r.get("id") in ("segment", "quote")),
        "segment",
    )
    root_vel_prefix = _vel_prefix_map.get(primary_root_id, "$data")
    if primary_root_id == "quote":
        validate_fqcn = f"{CUSTOMER_PACKAGE}.{product}Quote"
        validate_ok = _class_exists(classpath, validate_fqcn)
    else:
        validate_fqcn = segment_fqcn
        validate_ok = segment_ok

    # --- Render + write Java -------------------------------------------------
    class_name = f"{product}DocumentDataSnapshotPluginImpl"
    java_path = out_dir / f"{class_name}.java"
    out_dir.mkdir(parents=True, exist_ok=True)
    java_path.write_text(
        render_java(product, suggested_path.name,
                    quote_df_calls=quote_df_calls, policy_df_calls=policy_df_calls),
        encoding="utf-8",
    )

    # --- Categorise + validate variables -------------------------------------
    variables = suggested.get("variables") or []
    high_vars = [
        v for v in variables
        if (v.get("confidence") or "").lower() == "high"
        and (v.get("data_source") or "").strip()
    ]
    ignored_vars = [v for v in variables if v not in high_vars]

    high_results: list[tuple[dict, str, str]] = []
    for v in high_vars:
        if validate_ok:
            status, detail = validate_path(
                classpath, validate_fqcn, v.get("data_source") or "",
                root_prefix=root_vel_prefix,
            )
        else:
            status, detail = "warning", f"type {validate_fqcn} not found in JAR"
        high_results.append((v, status, detail))

    # --- Optional compile check ----------------------------------------------
    compile_status: str | None = None
    compile_detail = ""
    compile_ok = True
    if args.compile_check:
        compile_ok, compile_detail = compile_check(
            java_path, customer_jar, datamodel_jar, slf4j_jar,
            repo_root / "build" / "tmp" / "leg4-compile",
        )
        compile_status = "PASS" if compile_ok else "FAIL"

    # --- Report --------------------------------------------------------------
    report_path = suggested_path.parent / f"{stem}.plugin-report.md"
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    write_report(
        report_path,
        stem=stem,
        product=product,
        suggested_path=suggested_path,
        java_path=java_path,
        high_results=high_results,
        ignored_vars=ignored_vars,
        compile_status=compile_status,
        compile_detail=compile_detail,
        generated_at=generated_at,
    )

    print(f"Wrote {_rel(java_path, repo_root)}")
    print(f"Wrote {_rel(report_path, repo_root)}")
    print(
        f"Product={product}  high={len(high_results)}  ignored={len(ignored_vars)}"
        + (f"  compile={compile_status}" if compile_status else "")
    )

    if args.compile_check and not compile_ok:
        print("ERROR: compile check failed:\n" + compile_detail, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
